import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header'
import Providers from './components/Providers'

export const metadata: Metadata = {
  title: 'SHINX NEWS',
  description: 'Generated by Shinxdev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={`bg-gray-100 dark:bg-zinc-900 transition-full duration-700`}>
          <Header />
          <div className="max-w-6xl mx-auto">{children}</div>
        </body>
      </Providers>
    </html>
  )
}
